---
- name: Basic setup of fresh arch installation
  hosts: machine

  vars_files:
    - config.yml

  roles:
    - name: roles/basic_setup
    - name: roles/tools

  #post_tasks:
  #  - notify: Update official packages
  #- notify: Update AUR packages
