- name: Basic setup of fresh arch installation
  hosts: machine
  vars_files:
    - config.yml

  roles:
    #- name: roles/install
    #- name: roles/setup
    # - name: roles/system-update
    # - name: roles/dummy-env

  post_tasks:
    - name: Update all packages from official repositories
      become: true
      community.general.pacman:
        upgrade: true
        update_cache: true
      changed_when: false

    - name: Update all packages from AUR
      become: true
      become_user: aur_builder
      kewlfft.aur.aur:
        upgrade: true
        use: yay
        state: present
      changed_when: false
