---
- name: Basic setup of fresh arch installation
  hosts: vm

  vars_files:
    - config.yml

  roles:
    - name: roles/install
    - name: roles/setup

  # post_tasks:
  #  - notify: Update official packages
  # - notify: Update AUR packages
