---
- name: Update all packages from official repositories
  become: true
  community.general.pacman:
    upgrade: yes
    update_cache: yes
  when: update | default(false) | bool

- name: Update all packages from AUR
  become_user: aur_builder
  kewlfft.aur.aur:
    upgrade: true
    use: yay
    state: present
  changed_when: false
  when: update | default(false) | bool
