---
#TODO I am sure there's a less ugly way..
- name: Check if yay directory exists
  stat:
    path: path=/home/npc/yay
  register: dir

- name: Debug pkg_file_exists variable
  debug:
    var: dir

- name: Clone yay repository
  git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "/home/npc/yay"
    update: yes

- block:
    - name: Build yay using makepkg
      command:
        cmd: makepkg -p PKGBUILD #-si
        chdir: /home/npc/yay

    - name: Find the .pkg.tar file
      find:
        paths: /home/npc/yay
        patterns: "*.pkg.tar.zst"
        file_type: "file"
      register: pkg_file

    - name: Extract the file name
      set_fact:
        pkg_file_name: "{{ pkg_file.files[0].path | basename }}"

    - name: Install yay
      become: true
      command:
        cmd: pacman -U --noconfirm /home/npc/yay/{{ pkg_file_name }}
        chdir: /home/npc/yay
  when: dir.stat.isdir is defined and dir.stat.isdir

#TODO Check if aur_builder user exists

# Needed for executing mkpkg parts without root
- name: Create the `aur_builder` user
  become: true
  user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    mode: 0644
    validate: "visudo -cf %s"
