- name: Create a user without sudo access
  become: true
  ansible.builtin.user:
    name: {{ user_name }}
    groups: users
    shell: /bin/zsh
  create_home: true

- name: Setup user environment
  include_role:
    name: setup
  vars:
    ansible_user: {{ user_name }}