#- name: Check if user exists
#  getent:
#    database: passwd
#    key: "{{ username }}"
#    fail_key: false
#  register: user_check
#
#- debug:
#    var: user_check
#    #verbosity: 2

- name: Create user without sudo
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/bash
    password: "{{ user_password }}"
    create_home: yes
    state: present     # will checks here make sense?

#- name: Remove user 
#  become: yes
#  ansible.builtin.user:
#    name: "{{ username }}"
#    state: absent
#    remove: yes
##
#- name: Setup user environment
#  include_role:
#    name: setup
#  vars:
#    ansible_user: {{ user_name }}