#- name: Check if user exists
#  getent:
#    database: passwd
#    key: "{{ username }}"
#    fail_key: false
#  register: user_check
#
#- debug:
#    var: user_check
#    #verbosity: 2

- name: Create user without sudo
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/bash
    password: "{{ user_password }}"
    groups: graphical-forward
    create_home: yes
    state: present     # will checks here make sense?

- name: Add authorized key for user
  become: true
  authorized_key:
    user: "{{ username }}"
    #key: "{{ lookup('file', 'files/id_rechenknecht.pub') }}" # in our configuration, this gets provided
  
- import_tasks: tasks/zsh.yml
- import_tasks: tasks/mamba.yml
- import_tasks: tasks/set_defaults.yml
  #  vars:
  #    ansible_user: "{{ username }}"

- name: Copy README.md
  become: true
  become_user: "{{ username }}"
  ansible.builtin.copy:
    src: README.md
    dest: ~/README.md
    owner: "{{ username }}" # probably need to change to var where I assign this as default
    group: "{{ username }}"
    mode: "0644"
  

#- name: Remove user 
#  become: yes
#  ansible.builtin.user:
#    name: "{{ username }}"
#    state: absent
#    remove: yes