---
- name: Install dev packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: "{{ dev_packages }}"
    use: yay
    update_cache: true
    state: present
  changed_when: false
