---
- name: Configure host.
  hosts: vm #vm here instead?

  vars_files:
    #  - default.config.yml
    - config.yml

  tasks:
    - import_tasks: tasks/update.yml
    - import_tasks: tasks/base-packages.yml
    - import_tasks: tasks/yay.yml
    #- import_tasks: tasks/nvidia_gpu.yml
    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/other-packages.yml
    - import_tasks: tasks/other-services.yml
    - import_tasks: tasks/dev-packages.yml
    #- import_tasks: tasks/upgrade.yml
    #
    #
  post_tasks:
    - notify: Update official packages
    - notify: Update AUR packages
