---
- name: Change user's default shell to zsh
  become: true
  ansible.builtin.command:
    cmd: "chsh -s /usr/bin/zsh {{ ansible_facts['user_id'] }}"
  # changed_when: false

#- name: Create script to take inhibition lock on SSH connection
#  become: true
#  copy:
#    src: sshrc
#    dest: /etc/ssh/sshrc
#    mode: 0755
#
#- name: Configure SSH server to execute script on new connections
#  become: true
#  lineinfile:
#    path: /etc/ssh/sshd_config
#    regexp: "^ForceCommand"
#    line: ForceCommand /etc/ssh/sshrc
#
- name: Configure SSH server to execute script on new connections
  become: true
  blockinfile:
    path: /etc/ssh/sshd_config
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR FORCE COMMAND"
    block: |
      Match User {{ ansible_facts['user_id'] }}
          ForceCommand systemd-inhibit --who="SSH session" --why="Active user" --what=idle --mode=block zsh

- name: Copy nvidia-drm configuration
  become: true
  copy:
    src: nvidia-drm.conf
    dest: /etc/modprobe.d/nvidia-drm.conf
    mode: 0644
  #notify: Reboot server


- name: Check if ssh.socket is active
  command: systemctl is-active ssh.socket
  register: ssh_socket_status
  changed_when: false
  failed_when: >
    ssh_socket_status.rc != 0 and
    'inactive' not in ssh_socket_status.stdout