---
- name: Change user's default shell to zsh
  become: true
  ansible.builtin.command:
    cmd: "chsh -s /usr/bin/zsh {{ ansible_facts['user_id'] }}"

#- name: Create script to take inhibition lock on SSH connection
#  become: true
#  copy:
#    src: sshrc
#    dest: /etc/ssh/sshrc
#    mode: 0755
#
#- name: Configure SSH server to execute script on new connections
#  become: true
#  lineinfile:
#    path: /etc/ssh/sshd_config
#    regexp: "^ForceCommand"
#    line: ForceCommand /etc/ssh/sshrc
#
#- name: Configure SSH server to execute script on new connections
#  become: true
#  blockinfile:
#    path: /etc/ssh/sshd_config
#    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR FORCE COMMAND"
#    block: |
#      Match User *
#          ForceCommand /bin/bash -c "/etc/ssh/sshrc"
#
- name: Copy nvidia-drm configuration
  become: true
  copy:
    src: nvidia-drm.conf
    dest: /etc/modprobe.d/nvidia-drm.conf
    mode: 0644
  #notify: Reboot server
