---
- name: Change user's default shell to zsh
  become: true
  ansible.builtin.command:
    cmd: "chsh -s /usr/bin/zsh {{ ansible_facts['user_id'] }}"

- name: Create script to take inhibition lock on SSH connection
  become: true
  copy:
    src: sshrc
    dest: /etc/ssh/sshrc
    mode: 0755

- name: Configure SSH server to execute script on new connections
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^SessionRCCommand"
    line: "SessionRCCommand /etc/ssh/sshrc"

#- name: Restart SSH server
#  systemd:
#    name: sshd
#    state: restarted # check still throws connection timed out after execution
#
- name: Logout and login to apply new configurations
  block:
    - name: Logout
      meta: reset_connection

    #    - name: Wait for user to log back in
    #      pause:
    #        prompt: "Please log back in to apply the new shell. Press Enter when ready."
    #
    - name: Verify new shell
      ansible.builtin.command:
        cmd: echo $SHELL
      register: shell_output

    - name: Print new shell
      debug:
        msg: "New shell: {{ shell_output.stdout }}"
