- name: Copy .condarc - we use mamba but its conda under the hood
  copy:
    src: condarc
    dest: ~/.condarc
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: 0644