- name: Copy .nvim configurations
  ansible.builtin.copy:
    src: nvim/
    dest: ~/.config/nvim/
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: "0644"
