---
- name: Change user's default shell to zsh
  become: true
  ansible.builtin.command:
    cmd: "chsh -s /usr/bin/zsh {{ ansible_facts['user_id'] }}"
  # changed_when: false

- name: Add main user to appending the group 'graphical-forward'
  become: true 
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: graphical-forward
    append: yes

- name: Copy nvidia-drm configuration
  become: true
  copy:
    src: nvidia-drm.conf
    dest: /etc/modprobe.d/nvidia-drm.conf
    mode: "0644"
  when: inventory_hostname in groups['machines']
  
  #notify: Reboot server