# control which new users can connect graphically
- name: Add graphical-forward group
  become: true
  group:
    name: graphical-forward
    state: present

# Contains options for xforwarding
- name: Copy sshd
  become: true
  ansible.builtin.copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"