---
- name: Install base packages
  become: true
  community.general.pacman:
    name: "{{ base_packages }}"
    state: present
  changed_when: false


- name: Flush handlers update+upgrade before continuing
  meta: flush_handler