- name: Check if mamba environment exists
  ansible.builtin.shell: |
    source ~/.zshrc
    mamba env list | grep -q "{{ mamba_env_name }}"
  register: env_exists
  failed_when: env_exists.rc > 1
  args:
    executable: /bin/zsh

- name: Create mamba environment
  ansible.builtin.shell: |
    source ~/.zshrc
    mamba create --name {{ mamba_env_name }}
  args:
    executable: /bin/zsh
  when: env_exists.rc != 0
  

- name: Populate mamba environment
  ansible.builtin.shell: |
    source ~/.zshrc
    mamba install -y --name {{ mamba_env_name }} {{ item }}
  loop: "{{ mamba_programs | default([]) }}" 
  args:
    executable: /bin/zsh